API_KEY = ""
MODELO = "claude-sonnet-4-20250514"
BATCH_SIZE = 5

CLASIFICACIONES_VALIDAS = [
    "A CLASIFICAR", 
    "AMORTIZACION", 
    "ANULACION", 
    "COMPRA", 
    "CONSUMO", 
    "DIVIDENDOS", 
    "GASTOS", 
    "INTERESES DE CUENTA (-)", 
    "INTERESES DE CUENTA (+)", 
    "INTERESES TITULOS", 
    "REPAGO CAPITAL (AMORTIZACION)", 
    "REPAGO CAPITAL (COMPRA)", 
    "REPAGO CAPITAL (VENTA)", 
    "RETENCION TAX", 
    "SALDO INICIAL", 
    "TRANSF REALIZADA A CUENTA PROPIA", 
    "TRANSF RECIBIDA DESDE CUENTA PROPIA", 
    "TRANSF TITULOS A OTRA CUENTA PROPIA"
]

TIPOS_ACTIVO_VALIDOS = [
    "ACCIONES", 
    "ADR", 
    "BONOS", 
    "CEDEARS", 
    "DERIVADOS", 
    "OBLIGACIONES NEGOCIABLES", 
    "FCI", 
    "OTROS", 
    "N/A"
]

CLASIFICACIONES_FIFO = [
    "COMPRA", 
    "VENTA", 
    "REPAGO CAPITAL (VENTA)", 
    "REPAGO CAPITAL (AMORTIZACION)"
]
